swagger: "2.0"
info:
  description: "WiFi Robot API"
  version: "0.2.0"
  title: "WiFi Robot"
  contact:
    email: "contact@thingagora.org"
  license:
    name: "Simplified BSD License"
    url: "https://opensource.org/licenses/BSD-2-Clause"
host: "192.168.0.112"
basePath: "/"
tags:
- name: "LED"
- name: "STEPPER"
schemes:
- "http"
paths:
  /LED/{index}/ON:
    get:
      tags:
      - "LED"
      summary: "Turn LED ON"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /LED/{index}/OFF:
    get:
      tags:
      - "LED"
      summary: "Turn LED OFF"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /LED/{index}/BLINK/{count}:
    get:
      tags:
      - "LED"
      summary: "Blink LED"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "count"
        in: "path"
        description: "LED blink count, -1 for non stop"
        required: true
        type: "integer"
        format: "int32"
        default: -1
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /LED/{index}/POLL/{millis}:
    get:
      tags:
      - "LED"
      summary: "Set LED poll delay"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "millis"
        in: "path"
        description: "Poll delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 200
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /LED/{index}/BLINKON/{millis}:
    get:
      tags:
      - "LED"
      summary: "Set LED blink ON delay"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "millis"
        in: "path"
        description: "Delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 200
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /LED/{index}/BLINKOFF/{millis}:
    get:
      tags:
      - "LED"
      summary: "Set LED blink OFF delay"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of LED to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "millis"
        in: "path"
        description: "Delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 200
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /SERVO/{index}/{angle}:
    get:
      tags:
      - "SERVO"
      summary: "Make SERVO take a given angle"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of SERVO to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "angle"
        in: "path"
        description: "Angle in degrees"
        required: true
        type: "integer"
        format: "int32"
        default: 90
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /STEPPER/{index}/{steps}:
    get:
      tags:
      - "STEPPER"
      summary: "Make STEPPER motor run a fixed amount of steps"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of STEPPER to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "steps"
        in: "path"
        description: "Number of steps to perform, negative for reverse"
        required: true
        type: "integer"
        format: "int32"
        default: 200
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /STEPPER/{index}/POLL/{millis}:
    get:
      tags:
      - "STEPPER"
      summary: "Set STEPPER poll delay"
      parameters:
      - name: "index"
        in: "path"
        description: "Index of STEPPER to address"
        required: true
        type: "integer"
        format: "int32"
        default: 0
      - name: "millis"
        in: "path"
        description: "Poll delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 200
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /WHEELBOT/POLL/{millis}:
    get:
      tags:
      - "WHEELBOT"
      summary: "Set WHEELBOT poll delay. -1 to stop."
      parameters:
      - name: "millis"
        in: "path"
        description: "Poll delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 5
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /WHEELBOT/POLLMAX/{millis}:
    get:
      tags:
      - "WHEELBOT"
      summary: "Set WHEELBOT maximum poll delay."
      parameters:
      - name: "millis"
        in: "path"
        description: "Poll delay in milliseconds"
        required: true
        type: "integer"
        format: "int32"
        default: 1000
      responses:
        200:
          description: "success"
        400:
          description: "error"
  /WHEELBOT/STEER/{angle}:
    get:
      tags:
      - "WHEELBOT"
      summary: "Set WHEELBOT steer angle in degrees"
      parameters:
      - name: "angle"
        in: "path"
        description: "Angle in degrees"
        required: true
        type: "integer"
        format: "int32"
        default: 90
      responses:
        200:
          description: "success"
        400:
          description: "error"
